-- 1. Create the table if it doesn't exist
create table if not exists daily_reports (
  id bigint generated by default as identity primary key,
  date date not null default current_date,
  branch_name text not null,
  data jsonb,
  -- We include these here for new tables, but we'll also run ALTER commands below to ensure they exist on old tables
  region text,
  district text,
  dm_name text,
  unique(date, branch_name)
);

-- 2. Add columns if they are missing (Idempotent update)
alter table daily_reports add column if not exists region text;
alter table daily_reports add column if not exists district text;
alter table daily_reports add column if not exists dm_name text;

-- 3. Enable RLS
alter table daily_reports enable row level security;

-- 4. Create Policy (Drop first to avoid error if it exists)
drop policy if exists "Allow anonymous access" on daily_reports;

create policy "Allow anonymous access" 
on daily_reports
for all 
to anon 
using (true) 
with check (true);

-- Optional: Create an index for faster filtering by date or region
create index if not exists idx_daily_reports_date on daily_reports(date);
create index if not exists idx_daily_reports_region on daily_reports(region);
